anitama:
  url: https://app.anitama.net/rss/google
  xpath: //div[@id="area-content-article"]

bombdance:
  url: http://feeds.feedburner.com/bombdance
  xpath: //div[@class="post-body entry-content"]

maniahero:
  url: http://www.maniahero.com/?feed=rss2
  xpath: //div[@class="entry-content"]

gamerboom:
  url: http://gamerboom.com/feed
  xpath: //div[@class="cnt_body"]

youxiputao:
  url: http://youxiputao.com/feed
  xpath: //div[@class="info"]

youxichaguan:
  url: http://www.youxichaguan.com/rss.php
  xpath: //div[@class="arc-article-detail"]

jasondan:
  url: http://feed.cnblogs.com/blog/u/91938/rss
  xpath: //div[@id="cnblogs_post_body"]

jiqizhixin:
  url: http://www.jiqizhixin.com/rss
  xpath: //div[@class="al-article-content"]

9to5mac:
  url: https://9to5mac.com/feed
  xpath: //div[@class="post-body"]

idownloadblog:
  url: http://www.idownloadblog.com/feed
  xpath: //div[@class="entry"]

pixivision:
  url: http://www.pixivision.net/zh/rss
  xpath: //header[@class="am__header"]|//div[@class="am__body"]
